# ==========================================
# 1. Project & System Setup
# ==========================================
experiment_name: encoder_vision
seed: 0
device: cuda:0

horizon: 60           # 예측할 미래 궤적의 길이 (스텝 수)
vision_stride: 6
obs_horizon: 30
batch_size: 16
num_workers: 4

# state_dim: 9          # encoder(2) + marker_pose(6) + marker_valid(1)
state_dim: 2            # encoder(2)
velocity_dim: 2
image_width: 320
image_height: 240

# ==========================================
# 3. Network Architecture (DiT & Condition)
# ==========================================
d_model: 384           # DiT와 Condition 네트워크의 통일된 은닉 차원
n_heads: 6             # Attention 헤드 수 (384 // 64 = 6)
depth: 12              # DiT 블록의 깊이
dropout: 0.1           # Classifier-Free Guidance(CFG)를 위한 조건 마스킹 확률

# ==========================================
# 4. Diffusion Process
# ==========================================
ema_rate: 0.9999       # Exponential Moving Average 업데이트 비율

# ==========================================
# 4. Inference & Solver (Sampling)
# ==========================================
use_ema: True
solver : ode_dpmsolver++_2M
w_cfg : 1.0
inference_sampling_steps: 100   # 실시간성을 위해 100에서 30으로 하향 조정

# ==========================================
# 5. Checkpoint (가중치 설정)
# =======================================c===
# 가중치가 inference.py와 같은 폴더에 있으므로 상대 경로 사용
checkpoint_dir  : "."
checkpoint_step : 100000
tensorrt_ckpt_dir : "/models/tensorrt/0407"
# ==========================================
# 6. Hydra Setup (최소화)
# ==========================================
hydra:
  output_subdir: null
  run:
    dir: .
